# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Routes' do
pod 'AFNetworking'

  target 'RoutesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoutesUITests' do
    # Pods for testing
  end

end
